"""Add filename, size, file_path to file_uploads

Revision ID: 7bf12c04aba9
Revises: 27b639797116
Create Date: 2025-02-28 04:45:25.594999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf12c04aba9'
down_revision: Union[str, None] = '27b639797116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'automation_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('file_uploads', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('file_uploads', sa.Column('size', sa.BigInteger(), nullable=False))
    op.add_column('file_uploads', sa.Column('file_path', sa.String(length=255), nullable=False))
    op.alter_column('file_uploads', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('file_uploads', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'process'::character varying"))
    op.alter_column('roles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('roles', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('roles', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('roles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'process'::character varying"))
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.alter_column('file_uploads', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('file_uploads', 'file_path')
    op.drop_column('file_uploads', 'size')
    op.drop_column('file_uploads', 'filename')
    op.alter_column('actions', 'automation_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
